export const linkActionTypes = {
    FETCH_LINKS_REQUEST : "FETCH_LINKS_REQUEST",
    FETCH_LINKS_SUCCESS : "FETCH_LINKS_SUCCESS",
    FETCH_LINKS_FAILURE : "FETCH_LINKS_FAILURE",
    FETCH_TAGS_REQUEST  : "FETCH_TAGS_REQUEST",
    FETCH_TAGS_SUCCESS  : "FETCH_TAGS_SUCCESS",
    FETCH_TAGS_FAILURE  : "FETCH_TAGS_FAILURE",

    EDIT_LINK_REQUEST   : "EDIT_LINK_REQUEST",
    ADD_LINK_SUCCESS    : "ADD_LINK_SUCCESS",
    UPDATE_LINK_SUCCESS : "UPDATE_LINK_SUCCESS",
    EDIT_LINK_FAILURE   : "EDIT_LINK_FAILURE",

    DELETE_LINK_REQUEST : "DELETE_LINK_REQUEST",
    DELETE_LINK_SUCCESS : "DELETE_LINK_SUCCESS",
    DELETE_LINK_FAILURE : "DELETE_LINK_FAILURE",

    COUNT_SUCCESS : "COUNT_SUCCESS",
    COUNT_FAILURE : "COUNT_FAILURE",
}

export const messageActionTypes = {
    SET_MESSAGE      : 'SET_MESSAGE',
    CLEAR_MESSAGE    : 'CLEAR_MESSAGE'
}

export const  tagActionTypes = {
    FETCH_TAGS_REQUEST : "FETCH_TAGS_REQUEST",
    FETCH_TAGS_SUCCESS : "FETCH_TAGS_SUCCESS",
    FETCH_TAGS_FAILURE : "FETCH_TAGS_FAILURE"
}
